export const listColors: string[] = [
  '#45B3E7',
  '#0078ff',
  '#bd00ff',
  '#d696bb',
  '#fa3c4c',
  '#ff9a00',
  '#fff000',
  '#01ff1f',
  '#41bc66',
  '#967259',
  '#444444',
];

export const listIcons: string[] = [
  'format_list_bulleted',
  'bookmark',
  'push_pin',
  'card_giftcard',
  'cake',
  'school',
  'article',
  'money',
  'music_note',
  'people',
  'shopping_cart',
  'airplanemode_on',
  'train',
  'directions_bus',
];
